### ISSUE TITLE
"about_link" must have a selection of subfields error

### ISSUE THREAD

**Issue by sharmainemanalo** [margueriteroth/gatsby-prismic-starter-prist#1]
I followed all the steps in the readme, including the Prismic set up but can't get past this error.

`There was an error in your GraphQL query: Field "about_link" of type "PRISMIC__Linkable" must have a selection of subfields.`
`Did you mean "about_link { ... }"?` 
`File: src/pages/index.js:211:29`

I also tested switching back to the prist repo instead of using my own after I got this error, and it appears to output the same error too. Is there something I might be doing wrong?

**Comment by pccunny** [comment]
I have exactly the same issue. Is there a fix?
