### ISSUE TITLE
Project Crashes After Adding repositoryName Field

### ISSUE THREAD

**Issue by towardsuffering** [margueriteroth/gatsby-prismic-starter-prist#12]
I followed every step in the README file, but once I switched the 'prist' repo name to my repo name called 'cRotunno' the program compiles when running gatsby-develop, but the local server creashes.

**Comment by towardsuffering** [comment]
https://github.com/margueriteroth/gatsby-prismic-starter-prist/issues/11#issuecomment-546243720

**Comment by reformedot** [comment]
Same problem here, I can't run gatsby develop and edit. All running perfect if I don't change the "prist" repo name, but obviusly I can't add new posts

**Comment by regisaberbache** [comment]
I found the solution to the problem in [this answer](https://github.com/margueriteroth/gatsby-prismic-starter-prist/issues/5#issuecomment-578314236) to another thread.
To make it short, you have to fill your new Prismic repo with content before building. And make sure links are actual links.

**Comment by trybick** [comment]
Same issue. @regisaberbache solution fixed it.

**Comment by kylemhudson** [comment]
Same. Fixed when I [used the solution in this issue](https://github.com/margueriteroth/gatsby-prismic-starter-prist/issues/5).
