### ISSUE TITLE
@reach/router error

### ISSUE THREAD

**Issue by adamUpchurch** [margueriteroth/gatsby-prismic-starter-prist#3]
I'm getting this error. @reach/router is not even in the package.json - so I'm kind of lost of what to do.

I tried to npm install through github - still same issue.

```
$ npm install
npm WARN deprecated @types/graphql@14.5.0: This is a stub types definition. graphql provides its own type definitions, so you do not need this installed.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@reach%2frouter - User not found
npm ERR! 404
npm ERR! 404  '@reach/router@^1.2.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gatsby'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by margueriteroth** [comment]
Hi @adamUpchurch — sorry for the frustrations.

Did you install this via the Gatsby CLI or by cloning and npm installing?

**Comment by pccunny** [comment]
Hi thanks for getting back to me.

It was the home page 'about link:. I used the type link in prismics and not
rich text with links lol.

The code it is obvious...

My website live and running.
Added site map re directs and robots.txs

A great starter. Thank you

Regards Paul

**Comment by margueriteroth** [comment]
Happy you are liking it! Thanks again 😄

**Comment by margueriteroth** [comment]
Also — I'd love to see the site you're building! @pccunny

**Comment by pccunny** [comment]
At https://pcconsultingasia.com.

First draft. Learning to add Gatsby plugins.

Paul
